---

- name: Gather facts of remote host
  setup:
    gather_subset: all

# Install dependencies on the host
- name: Install pip
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"
# sudo apt-get update; sudo apt-get install python-pip

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest
# pip install --upgrade pip

- name: sudo apt-get install ['git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'vim', 'python3-pip', 'libblacs-mpi-dev', 'python3-venv', 'python-docker']
  tags: always
  become: yes
  apt:
    name: ['git', 'python3-dev', 'python3-pip', 'python3-setuptools', 'vim', 'python3-pip', 'libblacs-mpi-dev', 'python3-venv', 'python-docker']
    state: latest
    install_recommends: no
    update_cache: yes

#- name: pip3 install ['wheel', 'mpi4py']
#  command: pip3 install {{item}}
#  with_items:
#    - wheel
#    - mpi4py

# - name: pip install ['mpi4py']
#   become: yes
#   pip:
#     name: ['mpi4py']
#     state: latest
# pip install ['mpi4py']

