---
- name: setup couchdb cluster | step 1
  become: yes
  uri:
    url: http://{{ groups['masternode'][0] }}:5984/{{ cluster_name }}
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_pass }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    body: "{\"action\": \"enable_cluster\", \"bind_address\":\"0.0.0.0\",\
             \"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_pass }}\", \"port\": \"5984\",\
             \"remote_node\": \"{{ item }}\", \"node_count\": \"{{ groups['couchdb'] | length }}\",\
             \"remote_current_user\":\"{{ couchdb_user }}\", \"remote_current_password\":\"{{ couchdb_pass }}\"}"
    headers:
      Content-Type: "application/json"
  loop: "{{ groups['workers'] }}"

- name: setup couchdb cluster | step 2
  become: yes
  uri:
    url: http://{{ groups['masternode'][0] }}:5984/{{ cluster_name }}
    status_code: 201,409
    method: POST
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_pass }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    method: POST
    body: "{\"action\": \"add_node\", \"host\":\"{{ item }}\",\
             \"port\": \"5984\", \"username\": \"{{ couchdb_user }}\", \"password\":\"{{ couchdb_pass }}\"}"
    headers:
      Content-Type: "application/json"
  loop: "{{ groups['workers'] }}"

- name: steup couchdb cluster | step 3 -- finish
  become: yes
  uri:
    url: http://{{ groups['masternode'][0] }}:5984/{{ cluster_name }}
    status_code: 201
    method: POST
    user: "{{ couchdb_user }}"
    password:  "{{ couchdb_pass }}"
    force_basic_auth: yes
    return_content: yes
    body_format: json
    method: POST
    body: "{\"action\": \"finish_cluster\"}"
    headers:
      Content-Type: "application/json"
