---
# - name: remove container
#   docker_container:
#     name: sleepy3
#     state: absent

- name: Start a container with a couchdb
  become: yes
  docker_container:
    name: "{{ couchdb_container_name}}"
    image: "{{ couchdb_image }}"
    ports:
      - "{{couchdb_port}}:{{couchdb_port}}" # 80 due to change security_group later
      - "9100:9100"
      - "4369:4369"
    env:
      COUCHDB_PASSWORD: "{{ couchdb_pass }}"
      COUCHDB_USER: "{{ couchdb_user }}"
      NODENAME: "{{ ansible_host }}"
      COUCHDB_SECRET: "{{ couchdb_cookie }}"
#    volume:
