---
- hosts: localhost
  gather_facts: true

  roles:
    - role: add-NectarGroupKey

- hosts: instances
  vars_files:
    - host_vars/config.yaml
    - host_vars/deploy.yaml
    - host_vars/instances.yaml
  gather_facts: true

  roles:
     - role: add-proxy
     - role: install-dependencies
     - role: setup-docker
     - role: git-clone-source-repository
     - role: mount-volumes
