---
- hosts: localhost
  vars_files:
    - host_vars/deploy.yaml
  gather_facts: true

  roles:
    - role: common
    - role: remove-instances
    - role: remove-volumes
    - role: remove-security-groups
