---
- name: add github ssh key
  copy:
    src: "config/GitHubKey.pem"
    dest: /home/ubuntu/.ssh/GitHubKey
    owner: ubuntu
    group: ubuntu
    mode: 0600
# copy GitHub private key to server

- name: configure ssh to use ansible key for github.com
  template:
    src: "config/ssh_config"
    dest: /home/ubuntu/.ssh/config
    owner: ubuntu
    group: ubuntu
    mode: 0644
# configure ssh to use ansible key for github.com

- name: Creates ~COMP90024 directory
  file:
    path: '{{ remote_working_directory }}'
    state: directory

- name: pull clone
  shell: git clone git@github.com:yangxvlin/comp90024-project2.git --config core.sshCommand="ssh -i /home/ubuntu/.ssh/GitHubKey"
  args:
    chdir: '{{ remote_working_directory }}'

#- name: Remove GitHubKey
#  file:
#    path: /home/ubuntu/.ssh/GitHubKey
#    state: absent
