---
# tasks file for remove-volumes

# Remove volumes from vars
# host_vars\deploy.yaml line 47
- name: Remove volume(s) on NeCTAR
  os_volume:
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: absent
  loop: '{{ volumes }}'
  register: os_vol
