---
# tasks file for create-security-groups

# Remove security group rules
- name: Remove security group rules
  os_security_group_rule:
    security_group: '{{ item.name }}'
    protocol: '{{ item.protocol }}'
    port_range_min: '{{ item.port_range_min }}'
    port_range_max: '{{ item.port_range_max }}'
    remote_ip_prefix: '{{ item.remote_ip_prefix }}'
    state: absent
  loop: '{{ security_groups }}'

# Remove a security group
- name: Remove a security group
  os_security_group:
    name: '{{ item.name }}'
    description: '{{ item.description }}'
    state: absent
  loop: '{{ security_groups }}'
